;;; nujelly-theme.el --- nujelly theme for GNU Emacs 24 (deftheme)

;;; Commentary:

;; Author: endoffile78
;; Original Author: Mark Tran <mark.tran@gmail.com>
;; URL: http://github.com/endoffile78/color-theme-nujelly
;; Version: 1.1.15

;; Inspired by jellybeans: http://www.vim.org/scripts/script.php?script_id=2555.

;;; Code:

(deftheme nujelly "The ujelly color theme")

(let ((class '((class color) (min-colors 89)))
      (nujelly-fg "#ffffff")
      (nujelly-bg "#000000")
      (nujelly-blue-0 "#8fbfdc")
      (nujelly-green-0 "#99ad6a")
      (nujelly-green-1 "#447799")
      (nujelly-green-2 "#a8ff60")
      (nujelly-grey-0 "#888888")
      (nujelly-grey-1 "#7f7f7f")
      (nujelly-grey-2 "#151515")
      (nujelly-grey-3 "#1c1c1c")
      (nujelly-grey-4 "#363636")
      (nujelly-grey-5 "#444444")
      (nujelly-orange-0 "#ffb964")
      (nujelly-purple-0 "#8197bf")
      (nujelly-purple-1 "#474e90")
      (nujelly-purple-2 "#cd00cd")
      (nujelly-purple-3 "#540063")
      (nujelly-purple-4 "#a40073")
      (nujelly-red-0 "#cf6a4c")
      (nujelly-red-1 "#dd0093")
      (nujelly-red-2 "#de5577")
      (nujelly-red-3 "#ff73fd")
      (nujelly-yellow-0 "#fad07a")
      (nujelly-yellow-1 "#ffff00"))

  (custom-theme-set-faces
   'nujelly
   `(default ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(alchemist-test--failed-face ((,class (:foreground ,nujelly-red-0))))
   `(alchemist-test--success-face ((,class (:foreground ,nujelly-green-0))))
   `(company-preview-common ((,class (:foreground nil :background ,nujelly-purple-1))))
   `(company-scrollbar-bg ((,class (:background ,nujelly-grey-2))))
   `(company-scrollbar-fg ((,class (:background ,nujelly-grey-0))))
   `(company-tooltip ((,class (:foreground ,nujelly-fg :background ,nujelly-grey-2))))
   `(company-tooltip-common ((,class (:foreground ,nujelly-red-0 :background ,nujelly-grey-2))))
   `(company-tooltip-common-selection ((,class (:foreground ,nujelly-red-0 :background ,nujelly-purple-1))))
   `(company-tooltip-selection ((,class (:background ,nujelly-purple-1))))
   `(compilation-error ((,class (:foreground ,nujelly-red-0))))
   `(compilation-info ((,class (:foreground ,nujelly-yellow-0))))
   `(compilation-line-number ((,class (:foreground ,nujelly-grey-0))))
   `(compilation-mode-line-exit ((,class (:foreground ,nujelly-green-0))))
   `(compilation-mode-line-fail ((,class (:foreground ,nujelly-red-0))))
   `(compilation-mode-line-run ((,class (:foreground ,nujelly-yellow-0))))
   `(diredp-date-time ((,class (:foreground ,nujelly-fg))))
   `(diredp-deletion ((,class (:foreground ,nujelly-red-0 :background ,nujelly-bg))))
   `(diredp-dir-heading ((,class (:foreground ,nujelly-yellow-0 :background ,nujelly-bg))))
   `(diredp-dir-priv ((,class (:foreground ,nujelly-green-2 :background ,nujelly-bg))))
   `(diredp-exec-priv ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(diredp-file-name ((,class (:foreground ,nujelly-fg))))
   `(diredp-file-suffix ((,class (:foreground ,nujelly-fg))))
   `(diredp-link-priv ((,class (:foreground ,nujelly-fg))))
   `(diredp-number ((,class (:foreground ,nujelly-fg))))
   `(diredp-no-priv ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(diredp-rare-priv ((,class (:foreground ,nujelly-red-0 :background ,nujelly-bg))))
   `(diredp-read-priv ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(diredp-symlink ((,class (:foreground ,nujelly-red-3))))
   `(diredp-write-priv ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(emmet-preview-output ((,class (:background ,nujelly-purple-1))))
   `(elixir-atom-face ((,class (:foreground ,nujelly-blue-0))))
   `(erc-notice-face ((,class (:foreground ,nujelly-yellow-0))))
   `(erc-prompt-face ((,class (:foreground ,nujelly-fg))))
   `(erc-timestamp-face ((,class (:foreground ,nujelly-purple-0))))
   `(eshell-prompt ((,class (:foreground ,nujelly-red-0))))
   `(eshell-ls-directory ((,class (:weight normal :foreground ,nujelly-green-2))))
   `(eshell-ls-executable ((,class (:weight normal :foreground ,nujelly-red-0))))
   `(eshell-ls-product ((,class (:foreground ,nujelly-fg))))
   `(eshell-ls-symlink ((,class (:weight normal :foreground ,nujelly-purple-2))))
   `(fancy-battery-critical ((,class (:weight bold :foreground ,nujelly-red-0))))
   `(fancy-battery-charging ((,class (:weight bold :foreground ,nujelly-green-0))))
   `(fancy-battery-discharging ((,class (:weight bold :foreground ,nujelly-yellow-1))))
   `(font-lock-builtin-face ((,class (:foreground ,nujelly-blue-0))))
   `(font-lock-comment-face ((,class (:slant italic :foreground ,nujelly-grey-0))))
   `(font-lock-constant-face ((,class (:foreground ,nujelly-green-1))))
   `(font-lock-doc-face ((,class (:foreground ,nujelly-green-0))))
   `(font-lock-function-name-face ((,class (:foreground ,nujelly-yellow-0))))
   `(font-lock-keyword-face ((,class (:foreground ,nujelly-purple-0))))
   `(font-lock-preprocessor-face ((,class (:foreground ,nujelly-fg))))
   `(font-lock-string-face ((,class (:foreground ,nujelly-green-0))))
   `(font-lock-type-face ((,class (:foreground ,nujelly-orange-0))))
   `(font-lock-variable-name-face ((,class (:foreground ,nujelly-red-0))))
   `(font-lock-warning-face ((,class (:foreground ,nujelly-red-1))))
   `(font-lock-regexp-grouping-construct ((t (:foreground ,nujelly-yellow-0 :bold t))))
   `(font-lock-regexp-grouping-backslash ((t (:foreground ,nujelly-red-0 :bold t))))
   `(fringe ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(git-commit-comment-file ((,class (:foreground ,nujelly-fg))))
   `(git-commit-comment-heading ((,class (:foreground ,nujelly-yellow-0))))
   `(git-commit-summary ((,class (:foreground ,nujelly-fg))))
   `(header-line ((,class (:foreground ,nujelly-fg))))
   `(helm-buffer-file ((,class (:foreground ,nujelly-fg))))
   `(helm-buffer-process ((,class (:foreground ,nujelly-yellow-0))))
   `(helm-buffer-size ((,class (:foreground ,nujelly-fg))))
   `(helm-candidate-number ((,class (:foreground ,nujelly-fg :background ,nujelly-bg))))
   `(helm-ff-directory ((,class (:background ,nujelly-bg))))
   `(helm-ff-file ((,class (:foreground ,nujelly-fg))))
   `(helm-grep-lineno ((,class (:foreground ,nujelly-fg))))
   `(helm-match ((,class (:foreground ,nujelly-red-1 :background ,nujelly-bg))))
   `(helm-moccur-buffer ((,class (:foreground ,nujelly-yellow-0))))
   `(helm-selection ((,class (:background ,nujelly-purple-1))))
   `(helm-source-header ((,class (:foreground ,nujelly-yellow-0 :background ,nujelly-grey-3))))
   `(helm-swoop-target-line-face ((,class (:foreground ,nujelly-fg :background ,nujelly-grey-4))))
   `(helm-swoop-target-word-face ((,class (:foreground ,nujelly-red-1))))
   `(highlight-indentation-face ((,class (:background ,nujelly-grey-2))))
   `(highlight-indentation-current-column-face((,class (:background ,nujelly-grey-2))))
   `(hl-line ((,class (:background ,nujelly-grey-4))(t :weight bold)))
   `(hl-line-face ((,class (:background ,nujelly-grey-4))(t :weight bold)))
   `(isearch ((,class (:foreground ,nujelly-fg :background ,nujelly-red-1))))
   `(isearch-fail ((,class (:background ,nujelly-red-1))))
   `(ido-first-match ((,class (:foreground ,nujelly-yellow-0))))
   `(ido-only-match ((,class (:foreground ,nujelly-green-0))))
   `(ido-subdir ((,class (:foreground ,nujelly-fg))))
   `(ido-virtual ((,class (:foreground ,nujelly-purple-0))))
   `(js2-external-variable ((,class (:foreground ,nujelly-orange-0))))
   `(js2-magic-paren ((,class (:underline t))))
   `(lazy-highlight ((,class (:foreground ,nujelly-red-1 :background nil))))
   `(linum ((,class (:slant italic :foreground ,nujelly-grey-0))))
   `(magit-blame-heading ((,class (:foreground ,nujelly-grey-1 :background ,nujelly-grey-2))))
   `(magit-branch-local ((,class (:foreground ,nujelly-green-2))))
   `(magit-branch-remote ((,class (:foreground ,nujelly-green-2))))
   `(magit-section-heading ((,class (:foreground ,nujelly-yellow-0 :background ,nujelly-grey-2))))
   `(magit-diff-added ((,class (:foreground ,nujelly-green-0))))
   `(magit-diff-added-highlight ((,class (:foreground ,nujelly-green-0 :inherit (magit-section-highlight)))))
   `(magit-diff-context ((,class (:foreground ,nujelly-fg))))
   `(magit-diff-context-highlight ((,class (:foreground ,nujelly-fg :inherit (magit-section-highlight)))))
   `(magit-diff-file-heading ((,class (:weight normal :foreground ,nujelly-fg :background ,nujelly-bg))))
   `(magit-diff-file-heading-highlight ((,class (:weight normal :foreground ,nujelly-fg :background ,nujelly-grey-2))))
   `(magit-diff-hunk-heading ((,class (:foreground ,nujelly-yellow-0 :background ,nujelly-grey-2))))
   `(magit-diff-hunk-heading-highlight ((,class (:foreground ,nujelly-yellow-0 :background ,nujelly-grey-3))))
   `(magit-diff-lines-heading ((,class (:foreground ,nujelly-fg :background ,nujelly-purple-1))))
   `(magit-diff-removed ((,class (:foreground ,nujelly-red-0))))
   `(magit-diff-removed-highlight ((,class (:foreground ,nujelly-red-0 :inherit (magit-section-highlight)))))
   `(magit-diffstat-added ((,class (:foreground ,nujelly-green-0))))
   `(magit-diffstat-removed ((,class (:foreground ,nujelly-red-0))))
   `(magit-hash ((,class (:foreground ,nujelly-red-1))))
   `(magit-section-highlight ((,class (:background ,nujelly-grey-2))))
   `(match ((,class (:background ,nujelly-red-1))))
   `(minibuffer-prompt ((,class (:foreground ,nujelly-fg))))
   `(mode-line ((,class (:foreground ,nujelly-fg :background nil))))
   `(mode-line-inactive ((,class (:foreground ,nujelly-grey-4 :background nil))))
   `(org-checkbox ((,class (:foreground ,nujelly-green-0))))
   `(org-date ((,class (:foreground ,nujelly-purple-0))))
   `(org-done ((,class (:foreground ,nujelly-green-0))))
   `(org-level-1 ((,class (:foreground ,nujelly-red-2))))
   `(org-level-2 ((,class (:foreground ,nujelly-red-0))))
   `(org-level-3 ((,class (:foreground ,nujelly-red-0))))
   `(org-link ((,class (:foreground ,nujelly-blue-0))))
   `(org-special-keyword ((,class (:foreground ,nujelly-purple-0))))
   `(org-todo ((,class (:foreground ,nujelly-yellow-0))))
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,nujelly-fg))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground ,nujelly-yellow-1))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground ,nujelly-purple-0))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground ,nujelly-orange-0))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground ,nujelly-red-1))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground ,nujelly-yellow-0))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground ,nujelly-purple-1))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground ,nujelly-green-0))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground ,nujelly-blue-0))))
   `(region ((,class (:background ,nujelly-purple-1))))
   `(shm-current-face ((,class (:background ,nujelly-grey-4))))
   `(shm-quarantine-face ((,class (:background ,nujelly-red-1))))
   `(smerge-markers ((,class (:foreground ,nujelly-yellow-0 :background ,nujelly-grey-2))))
   `(smerge-refined-change ((,class (:foreground ,nujelly-green-0))))
   `(sp-pair-overlay-face ((,class (:background nil))))
   `(sp-show-pair-match-face ((,class (:background ,nujelly-grey-1))))
   `(trailing-whitespace ((,class (:background ,nujelly-red-1))))
   `(web-mode-builtin-face ((,class (:inherit font-lock-builtin-face))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,nujelly-purple-0))))
   `(web-mode-html-tag-face ((,class (:foreground ,nujelly-yellow-0))))
   `(web-mode-symbol-face ((,class (:foreground ,nujelly-green-1))))
   `(web-mode-doctype-face ((,class (:foreground ,nujelly-blue-0 :slant italic))))
   `(web-mode-html-tag-bracket-face ((,class (:foreground ,nujelly-fg))))
   `(web-mode-current-element-highlight-face ((,class (:background ,nujelly-grey-1))))
   `(web-mode-block-delimiter-face ((,class (:foreground ,nujelly-blue-0))))
   `(web-mode-warning-face ((,class (:inherit font-lock-warning-face))))
   `(web-mode-error-face ((,class (:background ,nujelly-red-1))))
   `(web-mode-comment-face ((,class (:inherit font-lock-comment-face))))
   `(web-mode-css-string-face ((,class (:inherit font-lock-string-face))))
   `(web-mode-block-comment-face ((,class (:inherit web-mode-comment-face))))
   `(web-mode-comment-keyword-face ((,class (:box 1 :weight bold))))
   `(web-mode-css-comment-face ((,class (:inherit web-mode-comment-face))))
   `(web-mode-javascript-comment-face ((,class (:inherit web-mode-comment-face))))
   `(web-mode-json-comment-face ((,class (:inherit web-mode-comment-face))))
   `(web-mode-function-call-face ((,class (:inherit font-lock-function-name-face))))
   `(whitespace-trailing ((,class (:background ,nujelly-red-1))))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'nujelly)

;;; nujelly-theme.el ends here
